### ISSUE TITLE
FAM Virtualization

### ISSUE THREAD

**Issue by sarsanaee** [FabricAttachedMemory/Emulation#12]
Dear all,

Actually, I have some questions which are related to FAM in the virtualization context and they are as follows:

- I want to know is it really necessary to virtualize FAM?!(We know that this project is an emulation to mimic the FABRIC ATTACH MEMORY behavior because the hardware is not available to everyone right now then we should emulate, maybe some people have access to this hardware but I do not :) ) 

- If we could build a system that could virtualize FAM then who cares about that?! (I think to myself how virtualization originated from the 60s for the reasons such as multiprogramming and high utilization and the high price of hardware and it has been keeping up with the cloud technologies and HPC and so). But today do we have the same aims to build a system for that?!
        **I guess if we could find sensible reasons to virtualized FAM then next step would be looking for current hypervisor support requirements and try to develop them with respect to the requirement and limitation. for instance, Is it possible for the current memory management components of hypervisors to support this amount of memory available in FAM**

- What are the probable use cases of virtualized FAM?

- And there are more challenges that could be discussed in this context but the question is to find reasons for FAM virtualization at first place.

Thank you

**Comment by coloroco** [comment]
Remember that FAME virtualizes the entire node, including the FAM.  I don't really understand the point you're making by focusing only on the FAM.   In both the real hardware for The Machine and FAME, the FAM appears as a contiguous memory range to the processor (real or virtualized).  This range is accessed via cache semantics, ie, a cache line at a time.

As The Machine is a prototype research project, we don't expect to build more than a handful of instances.  Access to them is tightly controlled and always overscheduled.   FAME was proposed as a development platform internally before hardware existed, and now can be used to expose The Machine environment and experience to a wider audience.

**Comment by sarsanaee** [comment]
![Stacks](https://user-images.githubusercontent.com/3644605/27410392-7c79bf40-56fc-11e7-9dcd-e2dcfdeff1bf.png)

Thank you for the explanation, probably I'm wrong but for more illustration, I uploaded an image containing two type of stacks:

The first one is the current stack is developed in this Github repo(Maybe I drew it wrong), and the second one is something else I guess. I want to know if it is a valid stack at first place, If yes, then Virtualized SOCs should see contiguous memory range provided by the underlying FAM and they should be able to communicate over this infrastructure. In this situation hypervisors is responsible for mapping objects in the memory for each virtualized SOC. Here are two questions,
**First:** Is the second stack is actually a valid one?
**Second**: What requirement we need to consider to make the hypervisors capable of mapping a large amount of memory in the real example? Presumably, hypervisor's current memory management mechanism could not scale. Possibly the second question could be answered if the corresponding stack is valid.

**Comment by coloroco** [comment]
Your "first stack" is close to the emulation model, but not quite right.  Refer to
[this page from the Emulation wiki](https://github.com/FabricAttachedMemory/Emulation/wiki/Emulation-via-Virtual-Machines) for a more accurate portrayal.   There are multiple copies of QEMU running, one for each node.   All QEMUs have a physical address space addendum via IVSHMEM.  Since they are all configured to use the same backing file, it's essentially a global shared memory space, just what we need for emulated FAM.

Now to your explicit questions:
**First:** No, I don't consider the second stack valid in this emulation environment.
**Second:** The hypervisor (in this case, the host kernel) is already capable of handling the shared memory mapping requests of all the QEMU processes (ie, virtual nodes).  You mentioned "scaling" in this question, is there a dataset of a particular size that you have in mind?

Do you believe something is missing from FAME that is necessary to achieve the desired results?  That's not the case.  We developed kernel modules with the x86 VMs that worked perfectly when rebuilt and used on the final ARM nodes.

**Comment by sarsanaee** [comment]
The emulation environment is alright and of course, it is capable of handling the shared memory. But in the **real deployment**, if virtualization is needed then what do you think? For example, is it possible to install KVM or Xen on SoCs and leverage the global shared memory in the virtual machines?!

In this emulation environment, SoCs are emulating the behaviors as well, but is virtualization easily supported by the system underneath when we have a real SoC? I guess it is not supported yet because hypervisors don't have the proper requirements currently. For instance, one other project at Hewlett-Packard Lab was related to **Virtual address space as the first-class citizen** and introduced in [this project](http://impact.crhc.illinois.edu/shared/Papers/ASPLOS16-SpaceJMP.pdf). It is ported to Linux and [Barrelfish ](http://www.barrelfish.org/)I guess. But in the virtualization context, something like that is needed for the hypervisors and is not available yet and they should be modified.

In order to emulate the topology I talked about with this emulation environment I think I should install a hypervisor in the virtual machines provided by the FAME and create virtual machines capable of talking to other SoCs(all VMs provided by the FAME other than the VM has **Hypervisor** installed) at first place.

Actually, It is another systems software powered by FAME as a versatile platform for this purpose.

**Comment by coloroco** [comment]
It sounds like you'd like to run VMs on the nodes of the real Machine hardware, and want to know if there's direct load/store MDC access from virtualized user applications to FAM.   I believe the answer is "That depends on the hypervisor setup".   In real hardware the hypervisor would have to be told about a file in LFS, which, if mmap()'d would give the desired access.   For qemu (on a real node) you'd use IVSHMEM again and I believe you'd get what you want.
