### ISSUE TITLE
vmdebootstrap error building node_template.img

### ISSUE THREAD

**Issue by john-wilkes** [FabricAttachedMemory/Emulation#16]
Handle VM golden image /tmp/node_template.img

Creating new /tmp/node_template.img from http://ftp.us.debian.org/debian
CRITICAL:root:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cliapp/app.py", line 179, in _run
    self.settings.load_configs()
  File "/usr/lib/python2.7/dist-packages/cliapp/settings.py", line 729, in load_configs
    s = self.set_from_raw_string(name, value)
  File "/usr/lib/python2.7/dist-packages/cliapp/settings.py", line 704, in set_from_raw_string
    s = self._settingses[name]
KeyError: 'sparse'

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cliapp/app.py", line 179, in _run
    self.settings.load_configs()
  File "/usr/lib/python2.7/dist-packages/cliapp/settings.py", line 729, in load_configs
    s = self.set_from_raw_string(name, value)
  File "/usr/lib/python2.7/dist-packages/cliapp/settings.py", line 704, in set_from_raw_string
    s = self._settingses[name]
KeyError: 'sparse'
Usage: vmdebootstrap [options]

vmdebootstrap: error: no such option: --debootstrapopts
sudo -E chown jwilkes /tmp/node.*
chown: cannot access '/tmp/node.*': No such file or directory
Error: Build of /tmp/node_template.img failed

**Comment by coloroco** [comment]
The error "vmdebootstrap: error: no such option: --debootstrapopts" makes me wonder what base operating system you're running on?

**Comment by john-wilkes** [comment]
Ubuntu 16.04 LTS

Apparently the default vmdebootstrap version is 0.2. I've downloaded the latest, 1.7, and will try with it.

I've seen some other incompatibilities along the way:
default qemu is version 2.0.0
qemu 2.6.2 installs in /usr/local/bin so that directory must be added to PATH in the script
qemu-bridge-helper lives in /usr/llocal/libexec, not /usr/lib/qemu
losetup does not have a "-al" command line option, change to "-a" or "-all"

**Comment by coloroco** [comment]
Most of our work has been on pure Debian, mostly Jessie.   There is a another recent user who is working on Ubuntu and is having similar issues.   We're trying to figure out the best way to proceed and your info is quite useful.

**Comment by coloroco** [comment]
If you are the "John Wilkes" attached to the Gen-Z consortium, would you please send me a direct email at rocky.craig@hpe.com?

**Comment by john-wilkes** [comment]
I misspoke: I was on Ubuntu 14.04 LTS. I installed 16.04, and emulation_configure.bash ran without errors after installing packages to resolve missing dependencies.
(Yes, I am "that" John Wilkes... I sent a separate email to you.)
