### ISSUE TITLE
Documenting request for test this Emulation environment

### ISSUE THREAD

**Issue by ysmiyake** [FabricAttachedMemory/Emulation#27]
AfterI install FAME and VMs seem to run properly,
we still annoyed to share memory from several processes on several nodes.
Though we saw software stack slide from THe Machine presentation, 
but it's hard to be corresponded on to one.
Could you give us what is(are) the minimum component(s) to test, for example which to be installed to run Sparkle?
We would like to know which software and libraries are required to share  memory from multiple nodes.
And also which APIs or functions should be call from processes.
We couldn't find any documents in github and these information will help users who try to test FAM(E).

**Comment by coloroco** [comment]
The next step is to configure and run the Librarian.  It is the central metadata server for the Librarian File System (LFS).  LFS is the global file system that manages FAM in both FAME and The Machine.

I'm adding code to create a reference INI file and will then update the Librarian README instructions here in this repo.

**Comment by coloroco** [comment]
The INI file is automatically created and there should be sufficient documentation in the Librarian.md file to get started.
