### ISSUE TITLE
vmdebootstrap-1.6: Use --image or --tarball, not both.

### ISSUE THREAD

**Issue by oaken-source** [FabricAttachedMemory/Emulation#8]
the latest release of vmdebootstrap (1.6 as from here: https://vmdebootstrap.alioth.debian.org/doc/overview.html) contains the following code:

```
        if self.settings['image'] and self.settings['tarball']:
            raise cliapp.AppException(
                'Use --image or --tarball, not both.')
```

which causes the `emulation_configure.bash` script to fail in line 300ff:

```
    quiet $VMD $VAROPT --log=$LOG --image=$TEMPLATE --tarball=$TARBALL \
        --mirror=$MIRROR --owner=$SUDO_USER
```

**Comment by coloroco** [comment]
We are finally moving to a base distribution (Sid) which has this new vmdebootstrap.  At this point we have determined there is no need for the tarball.   Look for a change which drops that argument.
